[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.exif", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.bcmath"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=80"
